version: '3.8'

x-db-environment: &x-db-environment
  MYSQL_RANDOM_ROOT_PASSWORD: "true"
  MYSQL_DATABASE: ${MYSQL_DATABASE}
  MYSQL_USER: ${MYSQL_USER}
  MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  MYSQL_PORT: 3306

x-wordpress-environment: &x-wordpress-environment
  WORDPRESS_DEBUG: "true"
  WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
  WORDPRESS_DB_USER: ${MYSQL_USER}
  WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
  WORDPRESS_DB_PORT: 3306

services:
  composer:
    build:
      context: ./.docker
      dockerfile: Dockerfile.composer
      args:
        PHP_VERSION: ${PHP_VERSION}
    restart: "no"
    user: ${CURRENT_UID}
    volumes:
      - ./:/app

  wordpress:
    image: wordpress:${WP_VERSION}-php${PHP_VERSION}
    restart: unless-stopped
    environment: &wordpress-environment
      <<: *x-wordpress-environment
      WORDPRESS_DB_HOST: db
    ports:
      - "${WEB_PUBLISHED_PORT}:80"
    volumes: &wordpress-volumes
      - ./:/var/www/html/wp-content/plugins/${COMPOSE_PROJECT_NAME}:cached
      - /var/www/html/wp-content/plugins/${COMPOSE_PROJECT_NAME}/.git
      - wordpress:/var/www/html
    depends_on:
      - db
    networks:
      - workspace

  wp:
    build:
      context: ./.docker
      dockerfile: Dockerfile.wp
      args:
        PHP_VERSION: ${PHP_VERSION}
    restart: "no"
    command: bash
    environment: *wordpress-environment
    volumes: *wordpress-volumes
    depends_on:
      - db
      - wordpress
    networks:
      - workspace

  db:
    image: mariadb:${MARIADB_VERSION}
    restart: unless-stopped
    environment: *x-db-environment
    ports:
      - "${DATABASE_PUBLISHED_PORT}:3306"
    volumes:
      - wordpress-db:/var/lib/mysql:delegated
    networks:
      - workspace

  codecept:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.codecept
      args:
        PHP_VERSION: ${PHP_VERSION}
        WP_VERSION: ${WP_VERSION}
    restart: "no"
    depends_on:
      - db-codecept
      - chrome
    environment:
      <<: *x-db-environment
      MYSQL_HOST: db-codecept
      MYSQL_DUMP: tests/_data/dump.sql
      <<: *x-wordpress-environment
      WORDPRESS_DB_HOST: db-codecept
      SELENIUM_HOST: chrome
      SELENIUM_PORT: 4444
      SELENIUM_BROWSER: chrome
      TEST_SITE_WP_URL: http://codecept
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
      WP_ROOT_FOLDER: ${WP_ROOT_FOLDER}
      TEST_TABLE_PREFIX: ${TEST_TABLE_PREFIX}
      TEST_SITE_WP_DOMAIN: ${TEST_SITE_WP_DOMAIN}
      TEST_SITE_ADMIN_EMAIL: ${TEST_SITE_ADMIN_EMAIL}
      TEST_SITE_WP_ADMIN_PATH: ${TEST_SITE_WP_ADMIN_PATH}
      TEST_SITE_ADMIN_USERNAME: ${TEST_SITE_ADMIN_USERNAME}
      TEST_SITE_ADMIN_PASSWORD: ${TEST_SITE_ADMIN_PASSWORD}
    volumes:
      - ./:/var/www/html/wp-content/plugins/${COMPOSE_PROJECT_NAME}/
      - /var/www/html/wp-content/plugins/${COMPOSE_PROJECT_NAME}/.git
    networks:
      - codecept

  db-codecept:
    image: circleci/mariadb:${MARIADB_VERSION}-ram
    restart: unless-stopped
    shm_size: '512mb'
    environment: *x-db-environment
    networks:
      - codecept

  chrome:
    image: selenium/standalone-chrome:4
    restart: unless-stopped
    shm_size: '2gb'
    networks:
      - codecept

networks:
  workspace:
  codecept:

volumes:
  wordpress:
    name: ${COMPOSE_PROJECT_NAME}-wordpress
    external: true
  wordpress-db:
    name: ${COMPOSE_PROJECT_NAME}-wordpress-db
    external: true
