name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php_version: ["7.4"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests
      run: make -j1 ci-codecept-run
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: codecept-output
        path: tests/_output/
        retention-days: 1
